name: "FD Pager"
description: "FD Pager"
version: "1.1.12"
slug: "ha-fd-pager"
init: false
hassio_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
  - i386
services:
  - mqtt:need
startup: services
ports:
  8000/tcp: 8000
options:
  general:
    api_url: ""
    api_token: ""
    verbosity: info
  mqtt:
    ha_autodiscovery_topic: homeassistant
    ha_status_topic: homeassistant/status
    base_topic: "fd-pager"
schema:
  general:
    api_url: str
    api_token: str
    verbosity: "list(debug|info|warning|critical|none)?"
  mqtt:
    host: "str?"
    port: "int?"
    user: "str?"
    password: str?
    tls_enabled: "bool?"
    tls_insecure: "bool?"
    tls_ca: "str?"
    tls_cert: "str?"
    tls_keyfile: "str?"
    ha_autodiscovery_topic: "str?"
    ha_status_topic: "str?"
    base_topic: "str?"