name: "FD Pager"
description: "FD Pager"
version: "1.1.0"
slug: "ha-fd-pager"
init: false
hassio_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
  - i386
services:
  - mqtt:need
startup: services
ports:
  8000/tcp: 8000
options:
  api_url: ""
  api_token: ""
  mqtt:
    ha_autodiscovery_topic: homeassistant
    ha_status_topic: homeassistant/status
    base_topic: "fd-pager"
schema:
  api_url: str
  api_token: str